CREATE DATABASE IF NOT EXISTS Agenda_Medica
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE Agenda_Medica;

CREATE TABLE IF NOT EXISTS Usuarios (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Usuario VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Rol VARCHAR(50) NOT NULL DEFAULT 'RECEPCION',
    Activo BOOLEAN NOT NULL DEFAULT TRUE,
    Fecha_Creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
